class Array8{

    public static void main(String[] args) {
        
        double[] data = new double[10];

        //declare and initialize and array
        int[] age = {12, 4, 5, 2, 5};

        // loop through the array
        // using for loop
        System.out.println("Using for-each Loop:");
        for(int a : age) {
            System.out.println(a);
        }
        // calculate the average
        // convert the average from int to double
         average =  ((double)sum / (double)arrayLength);

    }


}